apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: pedalpals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: notification-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
        
