apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
  namespace: pedalpals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
      - name: review
        image: review-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        
